//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicandoAplicada
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelo
    {
        public modelo()
        {
            this.servicio = new HashSet<servicio>();
            this.vehiculo = new HashSet<vehiculo>();
        }
    
        public int id_modelo { get; set; }
        public string annio { get; set; }
        public int id_marca { get; set; }
        public string nombre { get; set; }
    
        public virtual marca marca { get; set; }
        public virtual ICollection<servicio> servicio { get; set; }
        public virtual ICollection<vehiculo> vehiculo { get; set; }
    }
}
