//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicandoAplicada
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public stock()
        {
            this.serviciostock = new HashSet<serviciostock>();
        }
    
        public int id_stock { get; set; }
        public string detalle { get; set; }
        public string precio { get; set; }
        public string minimo { get; set; }
        public string cantidad { get; set; }
    
        public virtual ICollection<serviciostock> serviciostock { get; set; }
    }
}
