//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicandoAplicada
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposervicio
    {
        public tiposervicio()
        {
            this.servicio = new HashSet<servicio>();
        }
    
        public int id { get; set; }
        public string tipodeservicio { get; set; }
    
        public virtual ICollection<servicio> servicio { get; set; }
    }
}
