//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicandoAplicada
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo
    {
        public tipo()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int id_tipo { get; set; }
        public string detalle { get; set; }
    
        public virtual ICollection<empleado> empleado { get; set; }
    }
}
